In [12]:
import numpy as np
from env.spider_space import SpiderSpace

In [13]:
SpiderSpace.is_sequential(12+14,13+14)

False

In [14]:
state = np.array([[[0,0,1,0],[0,0,0,0],[0,0,0,0], [0,8,0,0]], 
                  [[0,0,1,0],[0,0,0,0],[0,0,0,0], [0,0,0,0]], 
                  [[0,0,0,0],[0,0,0,0],[0,0,0,0], [0,0,0,0]],
                  [[0,0,1,0],[0,0,0,0],[9,9,0,0], [0,0,0,0]], 
                  [[0,0,0,0],[9,9,0,0], [999,0,0,0],[0,0,0,0]],#shift by 1 position left
                  [[0,0,0,0],[0,0,0,0], [9,9,0,0], [999,0,0,0]] # shift by 2 pos left
                 ])
SpiderSpace._left_align_rows(state)

array([[[  0,   0,   1,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   8,   0,   0]],

       [[  0,   0,   1,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   1,   0],
        [  0,   0,   0,   0],
        [  9,   9,   0,   0],
        [  0,   0,   0,   0]],

       [[  9,   9,   0,   0],
        [999,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  9,   9,   0,   0],
        [999,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]]])

In [15]:
rows = np.array([0,1])
cols=np.array([0,1])
v = np.array([[22,3,34],
             [444,555,666]])
v[rows, np.array([[0,1],
                  [1,2]])]
v[0,1,None]=99
v

array([[ 22,  99,  34],
       [444, 555, 666]])

In [16]:
SpiderSpace._get_facedown_counts(np.array([[[-1,2],[3,9]], 
                                              [[-21,-23],[4,-4]]]))

array([[1, 0],
       [1, 2]])

In [17]:

spider = SpiderSpace(maxsize=50)
s = spider.sample()
# while not np.any(s[-1]==2):
#     s = spider.sample()
# # sorted(s.flatten())
np.count_nonzero(s, axis=1)
s[0, 0:2]=17+13
s[0, 2:4]=16+13
s[0, 4:6]=20
s[0, 6:7]=19

s[1, 4:6]=19
s[1, 2:4]=20+13
print(s[:2])
sv = SpiderSpace._vectorize(s, _counts_features=False)
SpiderSpace._get_max_sequences_depths(sv[:10])

[[ 30  30  29  29  20  20  19   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [-60 -95  33  33  19  19   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0]]


array([[0, 2, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0]])

In [18]:
SpiderSpace._left_align_rows(np.array([[0,1,0,2], 
                                      [9,0,-8,0]])) # works well with 2D but higher dimensions are supported poorly

array([[ 1,  0,  2,  0],
       [ 9,  0, -8,  0]])

In [19]:
# Getting top cards idcs and seq depths

import numpy as np
tableau_piles1D = np.array([1,4,3,15,14,13,12,0,0])

tableau_piles2D = np.array([[1,4,3,15,14,13,12,0,0],
                            [1,4,3,16,15,13,12,0,0],
                              [1,4,3,2,16,15,14,0,0],
                              [3,2,1,0,0,0,0,0,0],
                                [0,0,0,0,0,0,0,0,0],
                              [2,3,1,0,0,0,0,0,0],
                              [16,15,14,0,0,0,0,0,0],
                              [1,4,9,9,5,4,3,-2,9]])

tableau_piles3D = SpiderSpace._vectorize(tableau_piles2D, _counts_features=False)
#print(np.diff(tableau_piles3D, axis=1))
#@njit(inline='always')

# print(SpiderSpace._vectorize(tableau_piles, facedown_counts=False))
print(SpiderSpace._get_max_sequences_depths(tableau_piles3D))#SpiderSpace._vectorize(tableau_piles, facedown_counts=False))
#_get_max_sequences_depths(SpiderSpace._vectorize(tableau_piles, facedown_counts=False))

#tableau_piles[get_top_cards_incides(tableau_piles)]
idc = SpiderSpace._get_top_cards_indices(tableau_piles3D)
# tableau_piles2D[idc]

# _get_max_sequences_depths(tableau_piles2D)
idc

[[2 0 0 0]
 [2 0 0 0]
 [0 3 0 0]
 [3 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 3 0 0]
 [1 0 0 0]]


(array([0, 1, 2, 3, 5, 6, 7]),
 array([6, 6, 6, 2, 2, 2, 8]),
 array([0, 0, 1, 0, 0, 1, 0]))