In [3]:
import numpy as np
import sys 
from pathlib import Path
# adjust '..' to point to your repository root that contains the SpiderSolitaire package
sys.path.insert(0, str(Path('..').resolve()))
from env.spider_space import SpiderSpace

In [4]:
SpiderSpace.is_sequential(12+14,13+14)

False

In [5]:
state = np.array([[[0,0,1,0],[0,0,0,0],[0,0,0,0], [0,8,0,0]], 
                  [[0,0,1,0],[0,0,0,0],[0,0,0,0], [0,0,0,0]], 
                  [[0,0,0,0],[0,0,0,0],[0,0,0,0], [0,0,0,0]],
                  [[0,0,1,0],[0,0,0,0],[9,9,0,0], [0,0,0,0]], 
                  [[0,0,0,0],[9,9,0,0], [999,0,0,0],[0,0,0,0]],#shift by 1 position left
                  [[0,0,0,0],[0,0,0,0], [9,9,0,0], [999,0,0,0]] # shift by 2 pos left
                 ])
SpiderSpace._left_align_rows(state)

array([[[  0,   0,   1,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   8,   0,   0]],

       [[  0,   0,   1,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   1,   0],
        [  0,   0,   0,   0],
        [  9,   9,   0,   0],
        [  0,   0,   0,   0]],

       [[  9,   9,   0,   0],
        [999,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  9,   9,   0,   0],
        [999,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]]])

In [6]:
rows = np.array([0,1])
cols=np.array([0,1])
v = np.array([[22,3,34],
             [444,555,666]])
v[rows, np.array([[0,1],
                  [1,2]])]
v[0,1,None]=99
v

array([[ 22,  99,  34],
       [444, 555, 666]])

In [7]:
SpiderSpace._get_facedown_counts(np.array([[[-1,2],[3,9]], 
                                              [[-21,-23],[4,-4]]]))

array([[1, 0],
       [1, 2]])

In [8]:

spider = SpiderSpace(maxsize=50)
s = spider.sample()
# while not np.any(s[-1]==2):
#     s = spider.sample()
# # sorted(s.flatten())
np.count_nonzero(s, axis=1)
s[0, 0:2]=17+13
s[0, 2:4]=16+13
s[0, 4:6]=20
s[0, 6:7]=19

s[1, 4:6]=19
s[1, 2:4]=20+13
print(s[:2])
sv = SpiderSpace._vectorize(s, _counts_features=False)
SpiderSpace._get_max_sequences_depths(sv[:10])

[[ 30  30  29  29  20  20  19   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [-54 -78  33  33  19  19   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0]]


array([[0, 2, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [9]:
SpiderSpace._left_align_rows(np.array([[0,1,0,2], 
                                      [9,0,-8,0]])) # works well with 2D but higher dimensions are supported poorly

array([[ 1,  0,  2,  0],
       [ 9,  0, -8,  0]])

In [10]:
# Getting top cards idcs and seq depths

import numpy as np
tableau_piles1D = np.array([1,4,3,15,14,13,12,0,0])

tableau_piles2D = np.array([[1,4,3,15,14,13,12,0,0],
                            [1,4,3,16,15,13,12,0,0],
                              [1,4,3,2,16,15,14,0,0],
                              [3,2,1,0,0,0,0,0,0],
                                [0,0,0,0,0,0,0,0,0],
                              [2,3,1,0,0,0,0,0,0],
                              [16,15,14,0,0,0,0,0,0],
                              [1,4,9,9,5,4,3,-2,9]])

tableau_piles3D = SpiderSpace._vectorize(tableau_piles2D, _counts_features=False)
#print(np.diff(tableau_piles3D, axis=1))
#@njit(inline='always')

# print(SpiderSpace._vectorize(tableau_piles, facedown_counts=False))
print(SpiderSpace._get_max_sequences_depths(tableau_piles3D))#SpiderSpace._vectorize(tableau_piles, facedown_counts=False))
#_get_max_sequences_depths(SpiderSpace._vectorize(tableau_piles, facedown_counts=False))

#tableau_piles[get_top_cards_incides(tableau_piles)]
idc = SpiderSpace._get_top_cards_indices(tableau_piles3D)
# tableau_piles2D[idc]

# _get_max_sequences_depths(tableau_piles2D)
idc

[[2 0 0 0]
 [2 0 0 0]
 [0 3 0 0]
 [3 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 3 0 0]
 [1 0 0 0]]


(array([0, 1, 2, 3, 5, 6, 7]),
 array([6, 6, 6, 2, 2, 2, 8]),
 array([0, 0, 1, 0, 0, 1, 0]))

In [84]:
arr2D = np.array([[1,4,3,15,14,13,12,0,0],
                            [1,4,3,16,15,13,12,0,0],
                              [1,4,3,2,16,15,14,0,0],
                              [3,2,1,0,0,0,0,0,0],
                                [0,0,0,0,0,0,0,0,0],
                              [2,3,1,0,0,0,0,0,0],
                              [16,15,14,0,0,0,0,0,0],
                              [1,4,9,9,5,4,3,-2,9],
                              [0,0,0,0,0,0,0,0,0]])


def get_top_cards_indices(tableau_piles,
                              _return_difference: bool=False,
                                __NONCARD_VALUE=SpiderSpace.NONCARD_VALUE) :
    """ Returns positions of sequences (1 card or elements of ordered sequences) which can be moved to another pile.
    """
    idc_nonzero = np.nonzero(tableau_piles)
    if len(idc_nonzero[0]):
        d = np.append(np.diff(idc_nonzero)[0].astype(bool), True)
        return tuple(idc_nonzero[i][d] for i in range(len(idc_nonzero)))
    else:
        return None
    
# Old implementation for comparison (SpiderSpace._get_top_cards_indices)
def old_get_top_cards_indices(tableau_piles,
                              _return_difference: bool=False,
                                __NONCARD_VALUE=SpiderSpace.NONCARD_VALUE) :
        """ Returns positions of sequences (1 card or elements of ordered sequences) which can be moved to another pile.
                The output is `np.array` of shape `(N_PILES,)`
            params:
                tableau_piles: the first N_PILES of game state (tableau piles)
                _return_difference: if True, the function returns the tuple `(cards_indices, differences)`, where `differences` represents shifted differences between cards per each pile. The latter is used by `_get_max_sequences_depths(tableau_piles)` function.
                Example:
                >>> SpiderSpace._get_top_cards_indices(np.array([[1,4,3,15,14,13,12,0,0],
                            [1,4,3,16,15,13,12,0,0],
                              [1,4,3,2,16,15,14,0,0],
                              [3,2,1,0,0,0,0,0,0],
                                [0,0,0,0,0,0,0,0,0],
                              [2,3,1,0,0,0,0,0,0],
                              [16,15,14,0,0,0,0,0,0],
                              [1,4,9,9,5,4,3,-2,9]]))
                (array([0, 1, 2, 3, 5, 6, 7]), array([6, 6, 6, 2, 2, 2, 8]))
        """
        #determining arithmetic axis
        ar_axis = int(len(tableau_piles.shape)>1) #0 if tableau_piles is 1D array, 1 otherwise
        #difference between cards per each pile (to detect ascending sequences (-1))
        padded_tableau = SpiderSpace._pad_matrix(tableau_piles, ar_axis) 
        d = np.diff(padded_tableau, axis=ar_axis)# will be truncated
        idc_topcards = np.nonzero(d - __NONCARD_VALUE)
    
        mask = np.append(np.diff(idc_topcards[0]), 1).astype(bool) 
        bnd_coords = tuple(bnd_ax[mask] for bnd_ax in idc_topcards)
        return bnd_coords if not _return_difference else (bnd_coords, d)#[:,:-1])
from scipy.sparse import rand
def test_top_cards_indices(n_tests=100, random_matrix_shape=(10,10), random_matrix_density=0.2):
    for i in range(n_tests):
        sparse_matrix = rand(*random_matrix_shape, density=random_matrix_density, format='csr')
        arr = ((sparse_matrix.toarray() - (sparse_matrix.toarray()>0)*0.5)*SpiderSpace.HIGHEST_CARD).round().astype(int)
        # print(arr)
        #print(get_top_cards_indices(arr))
        #print(SpiderSpace._get_top_cards_indices(arr))
        arr3d = SpiderSpace._vectorize(arr, _counts_features=False)
        assert np.array_equal(get_top_cards_indices(arr), old_get_top_cards_indices(arr)), f"Test failed for iteration {i}, arr:\n{arr}"
        assert np.array_equal(get_top_cards_indices(arr3d), old_get_top_cards_indices(arr3d)), f"Test failed for iteration {i}, arr:\n{arr3d}"

        

test_top_cards_indices(1000000, random_matrix_density=0.1)
# print(get_top_cards_indices(arr2D))
# print(SpiderSpace._get_top_cards_indices(arr2D))
